project:
  name: quickstart-aviatrix-controller
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-aviatrix-master:
    parameters:
      AvailabilityZones: $[alfred_genaz_2]
      IAMRoleParam: New
      InstanceTypeParam: t2.large
      KeyNameParam: $[alfred_getkeypair]
      PublicSubnet1CIDR: 10.0.10.0/24
      PublicSubnet2CIDR: 10.0.20.0/24
      QSS3BucketName: $[taskcat_autobucket]
      VPCCIDR: 10.0.0.0/16
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/quickstart-aviatrix-nextgentransithub-controller-master.template
